version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo install step...
      - echo runtime-version is docker 20
  pre_build:
    commands:
      - printenv
      - echo $AccountId
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${AccountId}.dkr.ecr.eu-west-2.amazonaws.com
      - REPOSITORY_URI=${AccountId}.dkr.ecr.eu-west-2.amazonaws.com/breakthrough
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag frontend:latest $AccountId.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "[{\"name\":\"default\",\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}]" > imagedefinitions.json
artifacts:
  files:
    - "imagedefinitions.json