version: 0.2
phases:
  install:
    commands:
      - echo install step...
      - echo runtime-version is docker 20
  pre_build:
    commands:
      - printenv
      - echo $ACCOUNT_ID
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.eu-west-2.amazonaws.com
#      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.eu-west-2.amazonaws.com/breakthrough
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - "**/*"
  discard-paths: yes